rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - rbx
  - ruby-head
bundler_args: --without darwin --without development
gemfile:
  - Gemfile
before_script:
  - "sudo apt-get -qq -y install ngircd"
  - "service ngircd stop"
  - "ngircd -f spec/config/ngircd-unencrypted.conf"
  - "ngircd -f spec/config/ngircd-encrypted-gnutls.conf"
script: "bundle exec rake spec"