rvm:
  - 1.9.2
  - 1.9.3
bundler_args: --without darwin --without development
gemfile:
  - Gemfile
before_script:
  - "sudo apt-get install ngircd"
  - "echo 'starting unencrypted ircd...'"
  - "ngircd -t -f spec/config/ngircd-unencrypted.conf | cat"
  - "echo 'starting encrypted ircd...'"
  - "ngircd -t -f spec/config/ngircd-encrypted.conf | cat"
  - "ps aux | grep ngircd"
  - "sleep 1"
script: "bundle exec rake"